#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = bbxbrow
ASMTOOLS        = asmtoolsManager.asm
HTMLVIEW        = AWATCHER.goc GLBANIM.goc OpenClos.goc StatText.goc\
                  UIOften.goc scrapbk.goc HTMLVIEW.goc ImportG.goc\
                  UIAction.goc UIRare.goc LoadURL.goc
INIT            = INIT.goc
NAVIGATE        = BOOKCLAS.goc FAVORCLS.goc FAVORITE.goc BOOKMARK.goc\
                  NAVCACHE.goc NAVIGATE.goc
URLDOC          = LOCALPAG.goc URLDOC.goc
URLDOCCT        = URLDOCCT.goc
URLFETCH        = URLFETCH.goc
URLFRAME        = FRFETCH.goc URLFRAME.goc
URLTEXT         = URLTEXT2.goc URLTEXT.goc
UI_TO_RDFS      =
OBJS            = AWATCHER.obj GLBANIM.obj OpenClos.obj StatText.obj\
                  UIOften.obj scrapbk.obj HTMLVIEW.obj ImportG.obj\
                  UIAction.obj UIRare.obj LoadURL.obj INIT.obj BOOKCLAS.obj\
                  FAVORCLS.obj FAVORITE.obj BOOKMARK.obj NAVCACHE.obj\
                  NAVIGATE.obj LOCALPAG.obj URLDOC.obj URLDOCCT.obj\
                  URLFETCH.obj FRFETCH.obj URLFRAME.obj URLTEXT2.obj\
                  URLTEXT.obj
COMMON          = bookclas.goh bookmark.goh favorcls.goh favorite.goh\
                  glbanim.goh javascr.h prodgpc.goh prodndo.goh\
                  stattext.goh htmlv_ui.goh htmlview.goh importg.goh\
                  options.goh prodbbx.goh urlfetch.goh
MODULES         = ASMTOOLS
CMODULES        = htmlview init navigate urldoc urldocct urlfetch urlframe\
                  urltext
SRCS            = $(ASMTOOLS) $(HTMLVIEW) $(INIT) $(NAVIGATE) $(URLDOC)\
                  $(URLDOCCT) $(URLFETCH) $(URLFRAME) $(URLTEXT) $(COMMON)
LOBJS           =

PRODUCTS        = AB DBCS ABDBCS 

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif

#if exists(AB/$(DEPFILE))
#include "AB/$(DEPFILE)"
#endif

#if exists(DBCS/$(DEPFILE))
#include "DBCS/$(DEPFILE)"
#endif

#if exists(ABDBCS/$(DEPFILE))
#include "ABDBCS/$(DEPFILE)"
#endif
