#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = bbxbrow
ASMTOOLS        = asmtoolsManager.asm
HTMLVIEW        = AWATCHER.goc GLBANIM.goc HTMLVIEW.goc OpenClos.goc\
                  StatText.goc UIAction.goc UIOften.goc scrapbk.goc\
                  UIRare.goc ImportG.goc LoadURL.goc
INIT            = INIT.goc
NAVIGATE        = BOOKCLAS.goc FAVORCLS.goc BOOKMARK.goc NAVIGATE.goc\
                  FAVORITE.goc NAVCACHE.goc
URLDOC          = LOCALPAG.goc URLDOC.goc
URLDOCCT        = URLDOCCT.goc
URLFETCH        = URLFETCH.goc
URLFRAME        = FRFETCH.goc URLFRAME.goc
URLTEXT         = URLTEXT2.goc URLTEXT.goc
UI_TO_RDFS      =
OBJS            = AWATCHER.obj GLBANIM.obj HTMLVIEW.obj OpenClos.obj\
                  StatText.obj UIAction.obj UIOften.obj scrapbk.obj\
                  UIRare.obj ImportG.obj LoadURL.obj INIT.obj BOOKCLAS.obj\
                  FAVORCLS.obj BOOKMARK.obj NAVIGATE.obj FAVORITE.obj\
                  NAVCACHE.obj LOCALPAG.obj URLDOC.obj URLDOCCT.obj\
                  URLFETCH.obj FRFETCH.obj URLFRAME.obj URLTEXT2.obj\
                  URLTEXT.obj
COMMON          = bookclas.goh bookmark.goh favorcls.goh favorite.goh\
                  glbanim.goh javascr.h prodgpc.goh prodndo.goh\
                  stattext.goh urlfetch.goh htmlv_ui.goh prodbbx.goh\
                  options.goh htmlview.goh importg.goh
MODULES         = ASMTOOLS
CMODULES        = htmlview init navigate urldoc urldocct urlfetch urlframe\
                  urltext
SRCS            = $(ASMTOOLS) $(HTMLVIEW) $(INIT) $(NAVIGATE) $(URLDOC)\
                  $(URLDOCCT) $(URLFETCH) $(URLFRAME) $(URLTEXT) $(COMMON)
LOBJS           =

PRODUCTS        = AB 

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif

#if exists(AB/$(DEPFILE))
#include "AB/$(DEPFILE)"
#endif
