#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = bbxbrow
ASMTOOLS        = asmtoolsManager.asm
HTMLVIEW        = AWATCHER.goc GLBANIM.goc OpenClos.goc StatText.goc\
                  UIOften.goc scrapbk.goc HTMLVIEW.goc ImportG.goc\
                  LoadURL.goc UIAction.goc UIRare.goc
INIT            = INIT.goc
NAVIGATE        = BOOKCLAS.goc FAVORCLS.goc BOOKMARK.goc FAVORITE.goc\
                  NAVIGATE.goc NAVCACHE.goc
URLDOC          = LOCALPAG.goc URLDOC.goc
URLDOCCT        = URLDOCCT.goc
URLFETCH        = URLFETCH.goc
URLFRAME        = URLFRAME.goc FRFETCH.goc
URLTEXT         = MemStream.c URLTextInternal.h MemStream.h URLTEXT.goc\
                  URLTextLinks.goc URLTextPrint.goc URLTextImages.goc\
                  URLTextImageProgress.goc URLTextScript.goc\
                  URLTextClipboard.goc
UI_TO_RDFS      =
OBJS            = AWATCHER.obj GLBANIM.obj OpenClos.obj StatText.obj\
                  UIOften.obj scrapbk.obj HTMLVIEW.obj ImportG.obj\
                  LoadURL.obj UIAction.obj UIRare.obj INIT.obj BOOKCLAS.obj\
                  FAVORCLS.obj BOOKMARK.obj FAVORITE.obj NAVIGATE.obj\
                  NAVCACHE.obj LOCALPAG.obj URLDOC.obj URLDOCCT.obj\
                  URLFETCH.obj URLFRAME.obj FRFETCH.obj MemStream.obj\
                  URLTEXT.obj URLTextLinks.obj URLTextPrint.obj\
                  URLTextImages.obj URLTextImageProgress.obj\
                  URLTextScript.obj URLTextClipboard.obj
COMMON          = bookclas.goh bookmark.goh favorcls.goh favorite.goh\
                  glbanim.goh javascr.h prodgpc.goh prodndo.goh\
                  stattext.goh htmlv_ui.goh importg.goh options.goh\
                  prodbbx.goh urlfetch.goh htmlview.goh
MODULES         = ASMTOOLS
CMODULES        = htmlview init navigate urldoc urldocct urlfetch urlframe\
                  urltext
SRCS            = $(ASMTOOLS) $(HTMLVIEW) $(INIT) $(NAVIGATE) $(URLDOC)\
                  $(URLDOCCT) $(URLFETCH) $(URLFRAME) $(URLTEXT) $(COMMON)
LOBJS           =

PRODUCTS        = AB DBCS ABDBCS 

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif

#if exists(AB/$(DEPFILE))
#include "AB/$(DEPFILE)"
#endif

#if exists(DBCS/$(DEPFILE))
#include "DBCS/$(DEPFILE)"
#endif

#if exists(ABDBCS/$(DEPFILE))
#include "ABDBCS/$(DEPFILE)"
#endif
