#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = bsqp
MAIN            = bsqp.goc process.goc subcode.goc process.goh subcode.goh\
                  bsqp.goh
UI              = uimain.goc uimain.goh
UI_TO_RDFS      =
OBJS            = bsqp.obj process.obj subcode.obj uimain.obj
COMMON          =
MODULES         =
CMODULES        = Main UI
SRCS            = $(MAIN) $(UI) $(COMMON)
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
