##############################################################################
#
#
# PROJECT:      Test Applications
# MODULE:       Form UTF-8 Regression
# FILE:         formtest.gp
#
# AUTHOR:       Generated by ChatGPT
#
##############################################################################
#
# Permanent name:
name formtest.app
#
# Long filename:
longname "Form UTF-8 Test"
#
# Specify geode type:
type    appl, process, single
#
# Specify class name for application process.
class   FormTestProcessClass
#
# Specify application object.
appobj  FormTestApp
#
# Token:
tokenchars "TEST"
tokenid 16431
#

platform geos201

# Libraries:
library geos
library ui
library ansic
library text
library html4par

# Resources:
resource APPRESOURCE ui-object
resource INTERFACE ui-object

