#
# THIS FILE HAS BEEN GENERATED AUTOMATICALLY.
#
# If you edit it, you will lose your changes, should it be regenerated.
#
GEODE           = netm
ASM_TO_OBJS     = netmManager.asm
UI_TO_RDFS      =
SRCS            = netmUtils.asm netmStrings.asm netmSecondary.asm\
                  netmManager.asm netmInitExit.asm netmHooks.asm\
                  netmEntry.asm netmDisk.asm netmVariable.def\
                  netmConstant.def
OBJS            = netmManager.obj
LOBJS           =

SYSMAKEFILE     = geode.mk

#include <geos.mk>
#include <gpath.mk>

#if exists(local.mk)
#include "local.mk"
#else
#include <$(SYSMAKEFILE)>
#endif

#if exists($(DEPFILE))
#include "$(DEPFILE)"
#endif
